<?php

use Illuminate\Database\Seeder;

class empresa_juradaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('empresa_juradas')->insert(array(
            array( // row #0
                'id' => 43,
                'arti_id' => NULL,
                'estado' => 'D.J. Aceptada',
                'folio' => NULL,
                'empresa_id' => 1,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #1
                'id' => 4,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9651465,
                'empresa_id' => 2,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 12:21:22',
            ),
            array( // row #2
                'id' => 5,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 2,
                'jurada_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #3
                'id' => 21,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9643546,
                'empresa_id' => 2,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 12:22:53',
            ),
            array( // row #4
                'id' => 22,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 960601,
                'empresa_id' => 2,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:48:44',
            ),
            array( // row #5
                'id' => 23,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 160601,
                'empresa_id' => 2,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:47:06',
            ),
            array( // row #6
                'id' => 24,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 160601,
                'empresa_id' => 2,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:51:14',
            ),
            array( // row #7
                'id' => 25,
                'arti_id' => 54,
                'estado' => 'Declarada en proceso',
                'folio' => 160601,
                'empresa_id' => 2,
                'jurada_id' => 29,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:09:57',
            ),
            array( // row #8
                'id' => 38,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9758521,
                'empresa_id' => 3,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 13:07:42',
            ),
            array( // row #9
                'id' => 35,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 3,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #10
                'id' => 36,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 3,
                'jurada_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #11
                'id' => 37,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 3,
                'jurada_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #12
                'id' => 39,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 961001,
                'empresa_id' => 3,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:53:52',
            ),
            array( // row #13
                'id' => 40,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 161001,
                'empresa_id' => 3,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:51:49',
            ),
            array( // row #14
                'id' => 41,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 161001,
                'empresa_id' => 3,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-03-29 12:40:33',
            ),
            array( // row #15
                'id' => 42,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 161001,
                'empresa_id' => 3,
                'jurada_id' => 29,
                'created_at' => NULL,
                'updated_at' => '2019-03-29 12:41:06',
            ),
            array( // row #16
                'id' => 20,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 963101,
                'empresa_id' => 4,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 13:12:48',
            ),
            array( // row #17
                'id' => 31,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 10019017,
                'empresa_id' => 4,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:55:21',
            ),
            array( // row #18
                'id' => 32,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 4,
                'jurada_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #19
                'id' => 33,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 163101,
                'empresa_id' => 4,
                'jurada_id' => 20,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 12:56:30',
            ),
            array( // row #20
                'id' => 34,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 4,
                'jurada_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #21
                'id' => 27,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9845210,
                'empresa_id' => 4,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:17:50',
            ),
            array( // row #22
                'id' => 74,
                'arti_id' => NULL,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 4,
                'jurada_id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #23
                'id' => 44,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 10032231,
                'empresa_id' => 5,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:57:08',
            ),
            array( // row #24
                'id' => 45,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 5,
                'jurada_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #25
                'id' => 46,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9858927,
                'empresa_id' => 5,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 14:35:42',
            ),
            array( // row #26
                'id' => 47,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 971601,
                'empresa_id' => 5,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:56:47',
            ),
            array( // row #27
                'id' => 48,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 5,
                'jurada_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #28
                'id' => 49,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 5,
                'jurada_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #29
                'id' => 50,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 5,
                'jurada_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #30
                'id' => 51,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 5,
                'jurada_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #31
                'id' => 84,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 171601,
                'empresa_id' => 5,
                'jurada_id' => 33,
                'created_at' => NULL,
                'updated_at' => '2019-04-13 12:43:51',
            ),
            array( // row #32
                'id' => 54,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 6,
                'jurada_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #33
                'id' => 55,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 10017825,
                'empresa_id' => 6,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-26 09:18:38',
            ),
            array( // row #34
                'id' => 56,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 6,
                'jurada_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #35
                'id' => 57,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 6,
                'jurada_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #36
                'id' => 58,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 6,
                'jurada_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #37
                'id' => 59,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 6,
                'jurada_id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #38
                'id' => 85,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 61031626,
                'empresa_id' => 6,
                'jurada_id' => 33,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:38:45',
            ),
            array( // row #39
                'id' => 52,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 960501,
                'empresa_id' => 6,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 10:45:16',
            ),
            array( // row #40
                'id' => 76,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 265791,
                'empresa_id' => 6,
                'jurada_id' => 22,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:20:51',
            ),
            array( // row #41
                'id' => 53,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 260631,
                'empresa_id' => 6,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:20:31',
            ),
            array( // row #42
                'id' => 64,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 160201,
                'empresa_id' => 7,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:25:19',
            ),
            array( // row #43
                'id' => 65,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 160201,
                'empresa_id' => 7,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-03-29 12:49:05',
            ),
            array( // row #44
                'id' => 66,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 7,
                'jurada_id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #45
                'id' => 60,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 224171,
                'empresa_id' => 7,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:24:04',
            ),
            array( // row #46
                'id' => 61,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 7,
                'jurada_id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #47
                'id' => 75,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 232849,
                'empresa_id' => 7,
                'jurada_id' => 22,
                'created_at' => NULL,
                'updated_at' => '2019-03-30 10:24:44',
            ),
            array( // row #48
                'id' => 62,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9845622,
                'empresa_id' => 7,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 14:39:07',
            ),
            array( // row #49
                'id' => 63,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 960201,
                'empresa_id' => 7,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 13:32:22',
            ),
            array( // row #50
                'id' => 67,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 10025712,
                'empresa_id' => 8,
                'jurada_id' => 21,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:01:02',
            ),
            array( // row #51
                'id' => 68,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9851129,
                'empresa_id' => 8,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 14:40:17',
            ),
            array( // row #52
                'id' => 70,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 8,
                'jurada_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #53
                'id' => 71,
                'arti_id' => 53,
                'estado' => 'Pendiente por declarar',
                'folio' => NULL,
                'empresa_id' => 8,
                'jurada_id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            array( // row #54
                'id' => 72,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 164401,
                'empresa_id' => 8,
                'jurada_id' => 20,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 14:40:02',
            ),
            array( // row #55
                'id' => 69,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 964401,
                'empresa_id' => 8,
                'jurada_id' => 23,
                'created_at' => NULL,
                'updated_at' => '2019-03-21 13:35:36',
            ),
            array( // row #56
                'id' => 73,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 9846068,
                'empresa_id' => 9,
                'jurada_id' => 24,
                'created_at' => NULL,
                'updated_at' => '2019-03-22 14:41:03',
            ),
            array( // row #57
                'id' => 78,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 162301,
                'empresa_id' => 9,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:03:18',
            ),
            array( // row #58
                'id' => 77,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 162301,
                'empresa_id' => 9,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:02:54',
            ),
            array( // row #59
                'id' => 79,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 162501,
                'empresa_id' => 10,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:04:27',
            ),
            array( // row #60
                'id' => 80,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 162501,
                'empresa_id' => 10,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:04:51',
            ),
            array( // row #61
                'id' => 81,
                'arti_id' => 57,
                'estado' => 'D.J. Observada',
                'folio' => 175601,
                'empresa_id' => 11,
                'jurada_id' => 27,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:06:10',
            ),
            array( // row #62
                'id' => 82,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 175601,
                'empresa_id' => 11,
                'jurada_id' => 28,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:06:26',
            ),
            array( // row #63
                'id' => 83,
                'arti_id' => 55,
                'estado' => 'D.J. Aceptada',
                'folio' => 175601,
                'empresa_id' => 11,
                'jurada_id' => 29,
                'created_at' => NULL,
                'updated_at' => '2019-04-15 11:06:37',
            ),
        ));

    }
}
