<?php

use Illuminate\Database\Seeder;

class EmpresasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        \DB::table('empresas')->insert(array(
            array( // row #0
                'id' => 1,
                'rut' => '8276861-0',
                'name' => 'Hermann',
                'name_corto' => 'HEBF',
                'arti_id' => 27,
                'tipo' => 'Persona Natural',
                'actividad' => NULL,
                'direccion' => NULL,
                'region_id' => 15,
                'region' => 'Arica y Parinacota',
                'comuna_id' => NULL,
                'comuna' => NULL,
                'ciudad_id' => 1,
                'ciudad' => 'Villarrica',
                'codpostal' => 0,
                'email' => 'Hermann@Berkhoff.cl',
                'fono' => NULL,
                'fe_inicio' => NULL,
                'tipo_tri' => 'Art 14 Ter',
                'segmento' => 'Micro',
                'codigo' => '741200',
                'giro' => 'ACTIVIDADES DE CONTABILIDAD, TENEDUR0A DE LIBROS Y AUDITOR0A; ASESORAMIENTOS TRIBUTARIOS',
                'logo' => 'default_logo.jpg',
                'capital' => 100,
                'notario' => NULL,
                'fe_notario' => NULL,
                'repertorio' => NULL,
                'fe_diario' => NULL,
                'reg_comercio' => NULL,
                'notas' => '<p>Seeding: UserTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: TiposTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: AtributosTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: CiudadesTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: RegionesTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: ComunasTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: DesgirosTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: GirosTableSeeder</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Seeding: JuradasTableSeeder</p>',
                'deleted_at' => NULL,
                'created_at' => '2018-05-02 18:59:51',
                'updated_at' => '2018-05-23 15:29:34',
            ),
            array( // row #1
                'id' => 2,
                'rut' => '76066491-K',
                'name' => 'Asesorias y Servicios ASA Ltda',
                'name_corto' => 'ASA',
                'arti_id' => 28,
                'tipo' => 'Soc. de Responsabilidad Limitada',
                'actividad' => 'Asesorías y servicios integrales a Empresas en Contabilidad tributaria laboral y computacional',
                'direccion' => 'D. Portales N° 1383',
                'region_id' => 9,
                'region' => 'Araucania',
                'comuna_id' => NULL,
                'comuna' => NULL,
                'ciudad_id' => 2,
                'ciudad' => 'Temuco',
                'codpostal' => 0,
                'email' => 'asesorias@asatemuco.cl',
                'fono' => '45-2994321',
                'fe_inicio' => '2009-08-18',
                'tipo_tri' => 'Art. 14 A',
                'segmento' => 'Pequena',
                'codigo' => '741400',
                'giro' => 'ACTIVIDADES DE ASESORAMIENTO EMPRESARIAL Y EN MATERIA DE GESTION',
                'logo' => 'logo',
                'capital' => 10000000,
                'notario' => 'Alarcon',
                'fe_notario' => '2009-06-30',
                'repertorio' => '2706-09',
                'fe_diario' => '2009-07-09',
                'reg_comercio' => '668 vta. n° 638',
                'notas' => '<p>Algunas notas para ASa:</p>\r\n\r\n<p>\\r\\n\\r\\n</p>\r\n\r\n<p>Hay que poder ingresar varios giros del SII y datos de bancos&nbsp;</p>',
                'deleted_at' => NULL,
                'created_at' => '2018-05-02 19:05:35',
                'updated_at' => '2018-05-23 20:43:54',
            ),
            array( // row #2
                'id' => 3,
                'rut' => '76104329-3',
                'name' => 'Industrial y Comercial Cente',
                'name_corto' => 'Cente',
                'arti_id' => 28,
                'tipo' => 'Soc. de Responsabilidad Limitada',
                'actividad' => 'Fabrica de Productos plasticos',
                'direccion' => NULL,
                'region_id' => 9,
                'region' => 'Araucania',
                'comuna_id' => NULL,
                'comuna' => NULL,
                'ciudad_id' => 2,
                'ciudad' => 'Temuco',
                'codpostal' => 0,
                'email' => 'industrial@cente.cl',
                'fono' => '45-2923770',
                'fe_inicio' => '2010-07-13',
                'tipo_tri' => 'Art. 14 A',
                'segmento' => 'Mediana',
                'codigo' => '252090',
                'giro' => 'FABRICACI0N DE OTROS ART0CULOS DE PL0STICO',
                'logo' => 'logo',
                'capital' => 6000000,
                'notario' => NULL,
                'fe_notario' => NULL,
                'repertorio' => NULL,
                'fe_diario' => NULL,
                'reg_comercio' => NULL,
                'notas' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2018-05-23 21:59:52',
                'updated_at' => '2018-05-23 22:06:39',
            ),
        ));
    }
}
